### ISSUE TITLE
Error on applying Azure Stack policy module to an Azure Subscription's Resource Group

### ISSUE THREAD

**Issue by GirishPillai123** [Azure/AzureStack-Tools#126] opened 2017-03-24 13:30 UTC
I am trying to apply the Azure Stack policy module as per this link ( https://docs.microsoft.com/en-us/azure/azure-stack/azure-stack-policy-module ) onto my subscription, but get the following error. The tools download is from the public GitHub repo for Azure-Stack tools. Am I doing something wrong OR is this a bug?

PS C:\AzureStack-Tools-master> New-AzureRmPolicyAssignment -Name AzureStack -PolicyDefinition $policy -Scope /subscriptions/$s.Subscription.SubscriptionId/resourceGroups/$resourceGroupName
New-AzureRmPolicyAssignment : The pipeline has been stopped.
At line:1 char:1
+ New-AzureRmPolicyAssignment -Name AzureStack -PolicyDefinition $polic ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : CloseError: (:) [New-AzureRmPolicyAssignment], PipelineStoppedException
    + FullyQualifiedErrorId : Microsoft.Azure.Commands.ResourceManager.Cmdlets.Implementation.NewAzurePolicyAssignmentCmdlet
 
New-AzureRmPolicyAssignment : BadRequest : The subscription identifier 'Microsoft.Azure.Commands.Profile.Models.PSAzureContext.Subscription.SubscriptionId' exceeded the 
maximum length of '64' characters.
At line:1 char:1
+ New-AzureRmPolicyAssignment -Name AzureStack -PolicyDefinition $polic ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : CloseError: (:) [New-AzureRmPolicyAssignment], ErrorResponseMessageException
    + FullyQualifiedErrorId : BadRequest,Microsoft.Azure.Commands.ResourceManager.Cmdlets.Implementation.NewAzurePolicyAssignmentCmdlet
 

Thanks,
Girish.

**Comment by MatthewMcGlynn** [comment] 2017-04-26 21:35
Hey Girish,

It looks like you specified the scope of the policy as:
 -Scope /subscriptions/**$s.Subscription.SubscriptionId**/resourceGroups/$resourceGroupName

Instead, retrieve the subscription ID ahead of the scope request. 

The following example on the ReadMe may be helpful:

```
Import-Module .\AzureStack.Policy.psm1

Login-AzureRmAccount
$s = Select-AzureRmSubscription -SubscriptionName "<sub name>"
$subId = $s.Subscription.SubscriptionId

$policy = New-AzureRmPolicyDefinition -Name AzureStack -Policy (Get-AzureStackRmPolicy)

New-AzureRmPolicyAssignment -Name AzureStack -PolicyDefinition $policy -Scope /subscriptions/$subId

```

With the above, I was unable to reproduce any error. Closing at this time.

**Closed by MatthewMcGlynn** 2017-04-26 21:35 UTC
Labels: bug, in-progress, tool blocking
